-- Exportar de nuevo justo antes de cada campaña. No entregar esta lista a colaboradores.
-- Edad y zona solo aparecen con permiso de personalización vigente.
select email,consent_at as fecha_consentimiento,version,age_band as franja_edad,
 city as ciudad,case province_code
 when '02' then 'Albacete'
 when '03' then 'Alicante / Alacant'
 when '04' then 'Almería'
 when '01' then 'Araba / Álava'
 when '33' then 'Asturias'
 when '05' then 'Ávila'
 when '06' then 'Badajoz'
 when '07' then 'Illes Balears'
 when '08' then 'Barcelona'
 when '48' then 'Bizkaia'
 when '09' then 'Burgos'
 when '10' then 'Cáceres'
 when '11' then 'Cádiz'
 when '39' then 'Cantabria'
 when '12' then 'Castellón / Castelló'
 when '13' then 'Ciudad Real'
 when '14' then 'Córdoba'
 when '15' then 'A Coruña'
 when '16' then 'Cuenca'
 when '20' then 'Gipuzkoa'
 when '17' then 'Girona'
 when '18' then 'Granada'
 when '19' then 'Guadalajara'
 when '21' then 'Huelva'
 when '22' then 'Huesca'
 when '23' then 'Jaén'
 when '24' then 'León'
 when '25' then 'Lleida'
 when '27' then 'Lugo'
 when '28' then 'Madrid'
 when '29' then 'Málaga'
 when '30' then 'Murcia'
 when '31' then 'Navarra'
 when '32' then 'Ourense'
 when '34' then 'Palencia'
 when '35' then 'Las Palmas'
 when '36' then 'Pontevedra'
 when '26' then 'La Rioja'
 when '37' then 'Salamanca'
 when '38' then 'Santa Cruz de Tenerife'
 when '40' then 'Segovia'
 when '41' then 'Sevilla'
 when '42' then 'Soria'
 when '43' then 'Tarragona'
 when '44' then 'Teruel'
 when '45' then 'Toledo'
 when '46' then 'Valencia / València'
 when '47' then 'Valladolid'
 when '49' then 'Zamora'
 when '50' then 'Zaragoza'
 when '51' then 'Ceuta'
 when '52' then 'Melilla'
 when '99' then 'Fuera de España'
 end as provincia,province_code as codigo_provincia,profile_updated_at as perfil_actualizado
from private.marketing_audience where own_news order by email;
